import '@/styles/globals.css'

export const metadata = {
  title: 'Moon Tarot',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex'>
        <div className='bg-black flex-1'>{children}</div>
        </div>
        </body>
    </html>
  )
}
